# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)
geckolib_version=4.8.4
irons_lib_version=1.21.1-3.14.8

mod_id=irons_artifice
mod_name=Iron's Arms 'n Artifice
mod_license=All Rights Reserved
mod_version=1.21.1-1.0.0
mod_group_id=io.redspace
mod_logo_file=iaa_logo_gunmetal_lowres.png
